backend:
  engine: POSTGRESQL
  db: statdb
  user: "psqladmin@pgs-alzver-proj.privatelink.postgres.database.azure.com"
  port: 5432
  host: "pgs-alzver-proj.privatelink.postgres.database.azure.com"
  args: "--auth-host=scram-sha-256"

backendImage:
  name: acr2022alzver.azurecr.io/backend
  tag: v1

backendHPA:
  enabled: true
  minReplicas: 2
  maxReplicas: 15
  averageCPU: 40

frontend:
  replicas: 1

frontendImage:
  name: acr2022alzver.azurecr.io/frontend
  tag: v1

frontendHPA:
  enabled: true
  minReplicas: 2
  maxReplicas: 15
  averageCPU: 40

ingressController:
  port: 80

---
