backend:
  engine: POSTGRESQL
  db: statdb
  user: "psqladmin@pgs-alzver-proj-test.privatelink.postgres.database.azure.com"
  port: 5432
  host: "pgs-alzver-proj-test.privatelink.postgres.database.azure.com"
  args: "--auth-host=scram-sha-256"
  nodeenv: 'production'

backendImage:
  name: acr2022alzver.azurecr.io/backend
  tag: latest

backendHPA:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  averageCPU: 60

frontend:
  replicas: 1

frontendImage:
  name: acr2022alzver.azurecr.io/frontend
  tag: latest

frontendHPA:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  averageCPU: 60

ingressController:
  port: 8080

---
