"""empty message

Revision ID: 878c7f30c470
Revises:
Create Date: 2021-12-08 10:56:29.403774

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "878c7f30c470"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_value", sa.Date(), nullable=False),
        sa.Column("country_code", sa.String(length=3), nullable=False),
        sa.Column("confirmed", sa.Integer(), nullable=True),
        sa.Column("deaths", sa.Integer(), nullable=True),
        sa.Column(
            "stringency_actual",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
        ),
        sa.Column("stringency",
                  sa.Numeric(precision=10, scale=2),
                  nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_statistics_country_code"),
        "statistics",
        ["country_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_statistics_date_value"),
        "statistics",
        ["date_value"],
        unique=False,
    )
    op.create_table(
        "updates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("date_value", sa.Date(), nullable=False),
        sa.Column("records", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_updates_date_value"),
                    "updates", ["date_value"],
                    unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_updates_date_value"), table_name="updates")
    op.drop_table("updates")
    op.drop_index(op.f("ix_statistics_date_value"), table_name="statistics")
    op.drop_index(op.f("ix_statistics_country_code"), table_name="statistics")
    op.drop_table("statistics")
    # ### end Alembic commands ###
