version: '3.8'

services:
  reverseproxy:
    build:
      dockerfile: Dockerfile
      context: ./reverseproxy
    ports:
      - "8000:80"
    depends_on:
      - frontend
      - backend
      - db

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend

  backend:
    env_file: environment.env
    build:
      dockerfile: Dockerfile
      context: ./backend

  db:
    env_file: environment.env
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

