version: '3.8'

services:
  reverseproxy:
    build:
      dockerfile: Dockerfile
      context: ./traefik
    ports:
      - "8000:80"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    depends_on:
      - frontend
      - backend
      - db

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
      - traefik.port=80
    ports:
      - "80:80"

  backend:
    env_file: environment.env
    build:
      dockerfile: Dockerfile
      context: ./backend
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=PathPrefix(`/api/`)
      - traefik.port=5000
    ports:
      - "5000:5000"

  db:
    env_file: environment.env
    image: postgres:14.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

volumes:
  postgres_data:

