apiVersion: v1
kind: ConfigMap
metadata:
  name: proj-config
data:
  engine: 'POSTGRESQL'
  db: 'statdb'
  user: 'psqladmin@pgs-alzver-proj.privatelink.postgres.database.azure.com'
  port: '5432'
  host: 'pgs-alzver-proj.privatelink.postgres.database.azure.com'
  args: '--auth-host=scram-sha-256'
  node-env: 'production'
