apiVersion: v1
kind: ConfigMap
metadata:
  name: proj-config
data:
  engine: "POSTGRESQL"
  db: "statdata"
  user: "postgres@pgs-alzver-proj.postgres.database.azure.com"
  port: "5432"
  host: "pgs-alzver-proj.postgres.database.azure.com"
  args: "--auth-host=scram-sha-256"
