apiVersion: batch/v1
kind: Job
metadata:
  name: "migrate-job"
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "migrate-job-pod"
    spec:
      restartPolicy: Never
      containers:
        - name: db-migrate
          image: acr2022alzver.azurecr.io/backend:v1
          command: ["migrate.sh"]
