apiVersion: v1
kind: ConfigMap
metadata:
  name: proj-config
data:
  engine: {{ .Values.backend.engine }}
  db: {{ .Values.backend.db }} 
  user: {{ .Values.backend.user }}
  port: {{ .Values.backend.port }}
  host: {{ .Values.backend.host }}
  args: {{ .Values.backend.args }}
