apiVersion: batch/v1
kind: Job
metadata:
  name: "migrate-job"
spec:
  backoffLimit: 2
  template:
    metadata:
      name: "migrate-job-pod"
    spec:
      restartPolicy: Never
      activeDeadlineSeconds: 240
      ttlSecondsAfterFinished: 100
      containers:
        - name: db-migrate
          image: "{{ .Values.backendImage.name }}:{{ .Values.backendImage.tag }}"
          command: 
            - npm 
            - run
            - migrate
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: proj-config
                  key: nodeenv
            - name: DATABASE_ENGINE
              valueFrom:
                configMapKeyRef:
                  name: proj-config
                  key: engine
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: proj-config
                  key: db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: proj-config
                  key: user
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: proj-config
                  key: port
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: proj-config
                  key: host
            - name: POSTGRES_INITDB_ARGS
              valueFrom:
                configMapKeyRef:
                  name: proj-config
                  key: args
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: proj-secret
                  key: dbsec.txt
